// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-7DxmQoAjrXL3MkqzttiESPUcO2FJSOs',
    appId: '1:1061992090362:web:178fe3f2e5128c32bf5743',
    messagingSenderId: '1061992090362',
    projectId: 'login-d82fe',
    authDomain: 'login-d82fe.firebaseapp.com',
    storageBucket: 'login-d82fe.appspot.com',
    measurementId: 'G-CF9L4Y6FX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVeD5MIVxgNE1YfeoydwYvgRSlcO78TXs',
    appId: '1:1061992090362:android:e2599d8149b5a328bf5743',
    messagingSenderId: '1061992090362',
    projectId: 'login-d82fe',
    storageBucket: 'login-d82fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKRgQ-bIJJCScPAID-YD0l-XxhDDOj4HY',
    appId: '1:1061992090362:ios:36b26246913a1193bf5743',
    messagingSenderId: '1061992090362',
    projectId: 'login-d82fe',
    storageBucket: 'login-d82fe.appspot.com',
    iosBundleId: 'com.example.loginwithfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKRgQ-bIJJCScPAID-YD0l-XxhDDOj4HY',
    appId: '1:1061992090362:ios:36b26246913a1193bf5743',
    messagingSenderId: '1061992090362',
    projectId: 'login-d82fe',
    storageBucket: 'login-d82fe.appspot.com',
    iosBundleId: 'com.example.loginwithfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-7DxmQoAjrXL3MkqzttiESPUcO2FJSOs',
    appId: '1:1061992090362:web:48199431c35f7779bf5743',
    messagingSenderId: '1061992090362',
    projectId: 'login-d82fe',
    authDomain: 'login-d82fe.firebaseapp.com',
    storageBucket: 'login-d82fe.appspot.com',
    measurementId: 'G-7D579SPB7N',
  );
}
